VERSION_TAG = 1
BUILD_MACHINE := $(shell whoami)@$(shell hostname)
BUILD_DATE := $(shell date -u +"%d/%m/%Y, %H:%M")
GIT_COMMIT := $(shell git log --pretty=format:"%H" HEAD -1)
CLI_INFO = "\"Version $(VERSION_TAG) built on $(BUILD_MACHINE) at $(BUILD_DATE) \r\nCommit: $(GIT_COMMIT)\r\n\""

NEW_DEFS = -DVERSION_TAG="\"$(VERSION_TAG)\"" 